UBUNTU: [Config] fix FTBFS: NVM=y
BugLink: https://bugs.launchpad.net/bugs/1837626

Since the rebase on Ubuntu-4.15.0-56.62, drivers/nvme fails to build if
CONFIG_NVM is disabled:

In file included from /home/ppisati/linux/drivers/nvme/host/core.c:32:0:
/home/ppisati/linux/drivers/nvme/host/nvme.h: In function
'nvme_nvm_register_sysfs':
/home/ppisati/linux/drivers/nvme/host/nvme.h:502:6: error: 'ctrl' undeclared
(first use in this function)
  if (ctrl->subsys->cmic & (1 << 3))
      ^~~~
...

Signed-off-by: Paolo Pisati <paolo.pisati@canonical.com>